### ISSUE TITLE
Add validation for donations to EDEN's Treasury

### ISSUE THREAD

**Issue by JAMares** [edenia/eden-spend-explorer#424]
**Epic:**
//As a (role or type end-user), I'd like (goal/need) because...
// As a (role or type end-user), I want to be able to (do something), with that I'm goint to (get the value).

**Criteria:**
//Write the main purpose we discussed to do, this will orient better the person who is assigned to this issue.
//Add an image to illustrate the idea.

**Tasks:**

- [ ] Collecting the data about the donations to the Treasury
- [ ] Add the validation
- [ ] Testing the fix
