### ISSUE TITLE
UI/UX Improvements on the treasury chart | Mobile & Desktop

### ISSUE THREAD

**Issue by warnerHurtado** [edenia/eden-spend-explorer#425]
**Epic:**
As a guest and member, I'd like to see the treasury chart on mobile and desktop.
As a guest and member, I want to see the treasury chart in the correct position with the correct dimensions.

**Criteria:**
The main purpose of this fix is to show the chart in the best way for a better user experience.

-Mobile version:
![Image](https://user-images.githubusercontent.com/56526123/214148785-bb2bc4e9-fcb8-4cbb-8727-af49510426e4.png)

-Desktop version:
![Image](https://user-images.githubusercontent.com/56526123/214148974-e45b3276-1009-4b1f-8d25-4ae4c9a26165.png)

**Tasks:**

- [x] Add more margin between the chart and brush
- [x] change label syles of bruhs
- [x] Change the titles and icon positions
- [x] Testing the fix
