### ISSUE TITLE
Add the on-chain data from Treasury to all project charts

### ISSUE THREAD

**Issue by btcurenas** [edenia/eden-spend-explorer#431]
**Epic:**
As a Delegate, I'd like to see the treasury data reflected in all the charts of the Spend Explorer, with that the stats and overall the financial info will be more reliable and accurate.

**Criteria:**
We need to adjust the validation paramentes of the treasury account to be applied in every projection that Spend-explorer is showing to users. It's important to adjust this info not only in the backend query but also in the contents of the Help section where it's disposed the source of the account movements. This is an extension of the last issue #424.

**Tasks:**

- [ ] Collecting the data about the donations to the Treasury
- [ ] Replace the query filter to the correct one with the respective on-chain data
- [ ] Add the validation to all the charts and projections required
- [ ] Testing the feature
- [ ] Merge the new feature
